name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 3

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - name: Ensure color support detection
        run: node tests/environments.js
      - name: Install benchmark dependencies
        run: npm run install-benchmarks
      - name: Build benchmasrk scripts
        run: npm run build-benchmarks
      - name: Simple API calls
        run: node benchmarks/simple.mjs --expose-gc
      - name: Complex formatting expression
        run: node benchmarks/complex.mjs --expose-gc
      - name: Library module's init time
        run: node benchmarks/loading.mjs --expose-gc
      - name: Total loaded code size
        run: node benchmarks/size.mjs
